### ISSUE TITLE
Understanding the permutation in QRMumps

### ISSUE THREAD

**Issue by MaxenceGollier** [JuliaSmoothOptimizers/QRMumps.jl#106]
I am having a hard time to understand what permutation is automatically done in QRMumps. 
More precisely, I am trying to implement a `QLP` factorization in order to solve the least-norm problem 
```math
\min \|x\| \ \text{subject to } Ax = b.
```
This requires taking a QR factorization with a rank revealing column permutation if I understand correctly. 
My question is: are the permutations in QRMumps appropriate for this ? 
I have been trying to implement it for a while but can't get it to work on larger problems where specific permutations (I am guessing rank revealing ones) are necessary.

https://github.com/JuliaSmoothOptimizers/QRMumps.jl/blob/e45811442a0f7e555fd5def595b0d22b59adab2d/docs/src/control_parameters.md?plain=1#L22-L25

In all cases, perhaps the documentation could be a little more specific on the permutations performed ?

**Comment by dpo** [comment]
@abuttari Would you have a moment to help @MaxenceGollier here? We're trying to compute a complete orthogonal decomposition. Thanks!

**Comment by amontoison** [comment]
@MaxenceGollier @dpo 
A rank-revealing column permutation is computed during the factorization phase because it depends on the coefficients of A.
The permutation described in the documentation for the analysis phase aims to reduce the fill-in in the factors and is based only on the sparsity pattern of the sparse matrix A.

**Comment by abuttari** [comment]
yes, @amontoison is right, the column permutation in qrm is only meant to reduce the fill-in generated during the factorization. To the best of my knowledge, there is no sparse QR solver that also does a rank-revealing permutation during the factorization; this is way too complex to implement and, furthermore, as the drawback of increasing the fill-in and thus the operational complexity. SuiteSparseQR does some kind of reank-revealing QR factorization without permuting the columns of $A$ (it simply skips columns where $R$ has diagonal coefficients smaller than a prescribed threshold).
I imagine your $A$ matrix is rank-deficient? If not a plain, non rank-revealing QR factorization will work.

**Comment by MaxenceGollier** [comment]
Thank you @abuttari !
