### ISSUE TITLE
Retrieve the factors?

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/QRMumps.jl#72]
Is it possible to retrieve the L factor of a positive-definite matrix? Or the R factor of a QR?

**Comment by amontoison** [comment]
No, It's possible to retrieve the factors `L` or `R`. Factors have a specific sparse format for **multifrontal** decomposition.
@abuttari Is it possible to add a routine that returns the factors in CSC or COO format?

**Comment by abuttari** [comment]
there is a method called qrm_get_r in qr_mumps that returns the L or R factor in COO format. The C interface is missing but can be quickly added.

**Comment by amontoison** [comment]
It will be great to have it in the `C` interface.
We can't retrieve the `L` factor with the sparse Cholesky factorization of Julia (CHOLMOD).

**Comment by abuttari** [comment]
qr_mumps now has a C interface for the qrm_spfct_get_r method. Usage example (assuming factorization is already done):

```C
  struct zqrm_spmat_type_c R;
  int *cp;

  zqrm_spfct_get_r_c(&qrm_spfct, &R);
  zqrm_spfct_get_cp_c(&qrm_spfct, &cp);
  zqrm_spfct_get_rp_c(&qrm_spfct, &rp);

```
The first function call retrieves the R factor (=L') resulting from the factorization of the permuted matrix. The second and third function calls retrieve the column and row permutation respectively (they are the same for a Cholesky factorization. Therefore R[rp,cp] is the factor of A[rp,cp]. Everything is in the master branch

**Comment by dpo** [comment]
Fantastic! Thanks, @abuttari !

**Comment by amontoison** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/3325
