### ISSUE TITLE
SparseMatrixCOO type initialization method

### ISSUE THREAD

**Issue by MaxenceGollier** [JuliaSmoothOptimizers/QRMumps.jl#95]
In #89 It was suggested to add two new constructors. 
It has now been closed but it seems that the constructor with a SparseMatrixCOO has not been implemented ? 
It could be useful when we just require A to be in any sparse format so that we can call `qrm_spmat_init(A)` regardless of the sparse format type.

**Comment by amontoison** [comment]
The `SparseMatrixCOO` format is not a format available in `SparseArrays`.
Julia officially supports only sparse matrix in CSC format (`SparseMatrixCSC`).
We could add a constructor for `SparseMatrixCOO` with a package extension for `SparseMatrixCOO.jl`.

**Comment by amontoison** [comment]
It's fine to add an extension for `SparseMatrixCOO.jl`.
Can you do it?
I have examples with CUDA.jl and AMDGPU.jl in KrylovPreconditioners.jl: https://github.com/JuliaSmoothOptimizers/KrylovPreconditioners.jl/tree/main/ext

**Comment by MaxenceGollier** [comment]
I am working on a pull request.
I found a bug which I think comes from #91, when I initialize `spmat = qrm_spmat_init(m,n,rows,cols,vals)` with any values of `(m,n,rows,cols,vals)`, the finalizer throws the error
`error in running finalizer: ErrorException("The provided sparse matrix format is not supported.")`
I have the same issue when trying to add a constructor for the COO format type.

**Comment by amontoison** [comment]
We should temporary comment the call to `qrm_check(err)`.
Alfredo will this issue in the next release.
It's just the returned code `err` that is not initialized in the source of the C interface:
https://github.com/JuliaSmoothOptimizers/QRMumps.jl/pull/94#issuecomment-2075113758

**Comment by MaxenceGollier** [comment]
Solved in #98.
